# \u7AEF\u53E3
server:
  port: 8761

# \u5E94\u7528\u540D\u79F0
spring:
  application:
    name: eureka-server

eureka:
  instance:
    # \u4F7F\u7528 ip \u4EE3\u66FF\u5B9E\u4F8B\u540D
    prefer-ip-address: true
    # \u5B9E\u4F8B\u7684\u4E3B\u673A\u540D
    hostname: ${spring.cloud.client.ip-address}
    # \u5B9E\u4F8B\u7684 ID \u89C4\u5219
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    # \u662F\u5426\u5411\u6CE8\u518C\u4E2D\u5FC3\u6CE8\u518C\u81EA\u5DF1
    registerWithEureka: false
    # \u662F\u5426\u5411\u6CE8\u518C\u4E2D\u5FC3\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F
    fetchRegistry: false
    serviceUrl:
      # \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/