# \u7AEF\u53E3
server:
  port: 9000

# \u5E94\u7528\u540D\u79F0
spring:
  application:
    name: gateway-service

eureka:
  instance:
    # \u4F7F\u7528 ip \u4EE3\u66FF\u5B9E\u4F8B\u540D
    prefer-ip-address: true
    # \u5B9E\u4F8B\u7684\u4E3B\u673A\u540D
    hostname: ${spring.cloud.client.ip-address}
    # \u5B9E\u4F8B\u7684 ID \u89C4\u5219
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/